### ISSUE TITLE
Complete Editing Checklist

### ISSUE THREAD

**Issue by gilbertginsberg** [gilbertginsberg/fcc-editor-trial#1]
Editing Checklist 

- [] Refer to the freeCodeCamp publication editor handbook: https://medium.com/@quincylarson/cb5876d1ef23
- [] Read text, understand story, and start brewing headline + image ideas
- [] Run text through the Hemingway App and apply suggested edits where it makes sense
- [] Re-read text and apply your edits 
- [] Re-run text through Hemingway App; get grade level of 6 
- [] Make a great headline; use  https://coschedule.com/headline-analyzer
- [] Add great opening image and others throughout article that are thematically consistent; use http://finda.photo/ or https://www.pexels.com/
- [] Attach 5 tags to story 
- [] Add gif at end of article asking people to share your article
- [] Re-read text for any typos, grammatical mistakes, etc.
